### ISSUE TITLE
RPC探测发现 xxx主机开放Terminal Server Licensing服务

### ISSUE THREAD

**Issue by FinleyTang** [murphysecurity/RDL-detect#2]
这能说明RDL开放吗，对这个不太了解，烦请解释一下

**Comment by Franci4c0** [comment]
同问，验证后如何？可以使用 Get-WindowsFeature -Name RDS-Licensing

**Comment by f0r** [comment]
是的，RDL功能对应的服务是Terminal Server Licensing，开启后可以通过RPC枚举开放服务里是否包含Terminal Server Licensing来远程判断
